[package]
name = "adjiec/tax-check"
version = "0.1.0"
description = "Tax Check static frontend"
entrypoint = "webserver"

[dependencies]
"wasmer/static-web-server" = "1"

[fs]
"/public" = "dist"

[[command]]
name = "webserver"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"
